# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Arkady Pevzner
tagline:          'A Jekyll theme'
description:      'My personal website'
url:              http://arkadyp.github.io

author:
  name:           'Arkady Pevzner'
  url:            https://arkadyp.github.io

paginate:         5